# Generated by Django 5.1.1 on 2024-09-15 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
