# Generated by Django 5.1.1 on 2024-09-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='null', max_length=150),
            preserve_default=False,
        ),
    ]
