# Generated by Django 5.1.1 on 2024-10-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranimelist',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, default='2024-10-02 16:00'),
            preserve_default=False,
        ),
    ]
