# Generated by Django 5.1.1 on 2024-10-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_useranimelist_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranimelist',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
