# Generated by Django 5.1.1 on 2024-10-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_useranimelist_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranimelist',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
