# Generated by Django 5.1.1 on 2024-10-07 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_friendrequest_request_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='request_id',
        ),
    ]
