# Generated by Django 5.1.1 on 2024-10-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_friendlist_friends_alter_friendlist_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendlist',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
