# Generated by Django 5.1.1 on 2024-10-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_friendlist_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendlist',
            name='friends_ids',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
