# Generated by Django 5.1.1 on 2024-10-08 05:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_friendlist_friends_ids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendlist',
            name='friends_ids',
        ),
        migrations.AddField(
            model_name='friendlist',
            name='friends_ids',
            field=models.ManyToManyField(blank=True, related_name='friends_ids', to=settings.AUTH_USER_MODEL),
        ),
    ]
