# Generated by Django 5.1.1 on 2024-10-08 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_friendlist_friends_ids_friendlist_friends_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendlist',
            name='friends_ids',
        ),
        migrations.RemoveField(
            model_name='friendlist',
            name='timestamp',
        ),
    ]
