# Generated by Django 5.1.1 on 2024-10-09 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_follow_following_alter_follow_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
