# Generated by Django 5.1.1 on 2024-10-12 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_chat_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
