# Generated by Django 5.1.1 on 2024-10-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_friendrequest_is_accepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='room_name',
            new_name='room_name_1',
        ),
        migrations.AddField(
            model_name='chat',
            name='room_name_2',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
