# Generated by Django 5.1.1 on 2024-10-13 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_follow_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='followers',
        ),
    ]
