# Generated by Django 5.1.1 on 2024-10-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_tempdeletedanime_time_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempdeletedanime',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
